const Ddata = {
  discountItems: [
    {
      id: 22,
      cover: "/images/discount/discount-1.png",
      name: "BenuX 2022",
      price: 250,
      brand: "Ziaomi",
      rated: "73",
    },
    {
      id: 23,
      cover: "/images/discount/discount-2.png",
      name: "Sony TV 1080p",
      price: 450,
      brand: "Ziaomi",
      rated: "73",
    },
    {
      id: 24,
      cover: "/images/discount/discount-3.png",
      name: "Sony PS4",
      price: 50,
      brand: "Ziaomi",
      rated: "73",
    },
    {
      id: 25,
      cover: "/images/discount/discount-4.png",
      name: "Setgearr 2022",
      price: 100,
      brand: "Ziaomi",
      rated: "73",
    },
    {
      id: 26,
      cover: "/images/discount/discount-5.png",
      name: "Tony BGB",
      price: 20,
      brand: "Ziaomi",
      rated: "73",
    },
    {
      id: 27,
      cover: "/images/discount/discount-6.png",
      name: "RG products",
      price: 200,
      brand: "Ziaomi",
      rated: "73",
    },
    {
      id: 28,
      cover: "/images/discount/discount-7.png",
      name: "Ranasonic 2022",
      price: 300,
      brand: "Ziaomi",
      rated: "73",
    },
    {
      id: 29,
      cover: "/images/discount/discount-8.png",
      name: "Pune HD",
      price: 30,
      brand: "Ziaomi",
      rated: "73",
    },
    {
      id: 30,
      cover: "/images/discount/discount-9.png",
      name: "Sony CCTV",
      price: 80,
      brand: "Ziaomi",
      rated: "73",
    },
  ],
};
export default Ddata;
