const Sdata = {
  shopItems: [
    {
      id: 7,
      cover: "/images/shops/shops-1.png",
      name: "Mapple Earphones",
      price: "180",
      discount: "25",
      brand: "Ziaomi",
      rated: "73",
    },
    {
      id: 8,
      cover: "/images/shops/shops-2.png",
      name: "Vivo android one",
      price: "120",
      discount: "10",
      brand: "Ziaomi",
      rated: "732",
    },
    {
      id: 9,
      cover: "/images/shops/shops-3.png",
      name: "Sony Light",
      price: "20",
      discount: "50 ",
      brand: "Ziaomi",
      rated: "73",
    },
    {
      id: 10,
      cover: "/images/shops/shops-4.png",
      name: "Iphone",
      price: "999",
      discount: "10 ",
      brand: "Ziaomi",
      rated: "734",
    },
    {
      id: 11,
      cover: "/images/shops/shops-5.png",
      name: "Ceats wireless earphone",
      price: "80",
      discount: "20 ",
      brand: "Ziaomi",
      rated: "730",
    },
    {
      id: 12,
      cover: "/images/shops/shops-7.png",
      name: "Redimi Phone",
      price: "400",
      discount: "20 ",
      brand: "Ziaomi",
      rated: "83",
    },
    {
      id: 13,
      cover: "/images/shops/shops-8.png",
      name: "Xeats Bluetooth earphones",
      price: "60",
      discount: "5 ",
      brand: "Ziaomi",
      rated: "242",
    },
    {
      id: 14,
      cover: "/images/shops/shops-9.png",
      name: "Airpod",
      price: "120",
      discount: "10",
      brand: "Ziaomi",
      rated: "23",
    },
    {
      id: 15,
      cover: "/images/shops/shops-10.png",
      name: "Silver Cap",
      price: "5",
      discount: "2",
      brand: "Ziaomi",
      rated: "884",
    },
  ],
};
export default Sdata;
