const Data = {
  productItems: [
    {
      id: 1,
      discount: 50,
      cover: "/images/flash/flash-1.png",
      name: "Shoes",
      price: 100,
      brand: "Ziaomi",
      rated: "84",
    },
    {
      id: 2,
      discount: 40,
      cover: "/images/flash/flash-2.png",
      name: "Watch",
      price: 20,
      brand: "Ziaomi",
      rated: "22",
    },
    {
      id: 3,
      discount: 40,
      cover: "/images/flash/flash-3.png",
      name: "Smart Mobile Black",
      price: 200,
      brand: "Ziaomi",
      rated: "63",
    },
    {
      id: 4,
      discount: 40,
      cover: "/images/flash/flash-4.png",
      name: "Smart Watch Black",
      price: 50,
      brand: "Ziaomi",
      rated: "192",
    },
    {
      id: 5,
      discount: 50,
      cover: "/images/flash/flash-1.png",
      name: "Shoes",
      price: 100,
      brand: "Ziaomi",
      rated: "2034",
    },
    {
      id: 6,
      discount: 50,
      cover: "/images/flash/flash-3.png",
      name: "Shoes",
      price: 100,
      brand: "Ziaomi",
      rated: "6231",
    },
  ],
};
export default Data;
